services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: base-image

  frontend:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        BASE_IMAGE: base-image
    ports:
      - '80:80'
    depends_on:
      - base

  backend:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        BASE_IMAGE: base-image
    ports:
      - '3000:3000'
    depends_on:
      - base
